Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-12, with the labels that each got.

#593 Metapool/mpeth
  data/mpETH/data.json
  data/mpETH/logo.svg
Labels: Stale

#588 Add Flux blockchain
  data/FLUX/data.json
  data/FLUX/logo.svg
Labels: base

#587 Add LUSD Base Contract
  data/LUSD/data.json
Labels: base

#577 adding mintable base erc20 contract address of ARPA
  data/ARPA/data.json
Labels: Stale, base

#589 add ether.fi weETH for Base mainnet
  data/weETH/data.json
Labels: base

#565 DRODEC Token for OP & Base
  data/DRODEC/data.json
  data/DRODEC/logo.svg
Labels: base

#597 add ether.fi weETH for Base mainnet
  data/weETH/data.json
Labels: base

#607 Add SIPHER to Superchain tokenlist
  data/SIPHER/data.json
  data/SIPHER/logo.svg
Labels: base
