Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-09, with the labels that each got.

#499 Add PIP token to BASE GOERLI
  data/PIP/data.json
Labels: base

#493 Add NFD to token registry
  data/NFD/data.json
  data/NFD/logo.svg
Labels: base

#503 add bwAJNA token
  data/bwAJNA/data.json
  data/bwAJNA/logo.svg
Labels: base

#498 Add TOWER token's Mainnet (Base) Address
  data/TOWER/data.json
Labels: base

#496 Base OpenX
  data/wOpenX/data.json
Labels: base-goerli, base

#497 Updated base goerli CHAIN token address
  data/CHAIN/data.json
Labels: base

#487 Add D2D token to Base
  data/D2D/data.json
  data/D2D/logo.svg
Labels: base

#500 Add 1INCH Token
  data/1INCH/data.json
  data/1INCH/logo.svg
Labels: base

#522 Add SAIL token
  data/SAIL/data.json
  data/SAIL/logo.png
Labels: waiting-for-pr-author-response

#507 Add WAMPL token to Base Bridges
  data/WAMPL/data.json
  data/WAMPL/logo.svg
Labels: waiting-for-pr-author-response, base

#514 Add Empower (MPWR) on Base
  data/MPWR/data.json
  data/MPWR/logo.svg
Labels: base

#518 added PIP to BASE
  data/PIP/data.json
Labels: base

#521 Add base L2 token address for KNC
  data/KNC/data.json
Labels: base

#504 Add BTRST
  data/BTRST/data.json
  data/BTRST/logo.svg
Labels: base

#525 Add ISK token
  data/ISK/data.json
  data/ISK/logo.svg
Labels: base-goerli, base

#524 Taminater new mta token
  data/MTA/data.json
Labels: base

#532 Add JRT token to Base
  data/JRT/data.json
  data/JRT/expectedMismatches.json
Labels: base

#519 add PRIME token as layerzero bridged token
  data/PRIME/data.json
  data/PRIME/logo.svg
Labels: base
