Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-11, with the labels that each got.

#555 ALI token added (goerli/base-goerli)
  data/ALI/data.json
  data/ALI/logo.png
Labels: base-goerli

#566 Add wstETH BASE
  data/wstETH/data.json
Labels: base

#573 add OCEAN
  data/OCEAN/data.json
  data/OCEAN/logo.png
Labels: waiting-for-pr-author-response

#575 add ether.fi weETH for Etherum mainnet and Optimism mainnet
  data/weETH/data.json
Labels: Stale

#574 Add AMKT to Base
  data/AMKT/data.json
Labels: base
