Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-07, with the labels that each got.

#404 Add rsr
  data/RSR/data.json
Labels: base-goerli

#405 Add ethplus
  data/ETH+/data.json
  data/ETH+/logo.png
Labels: base-goerli

#406 Add eusd
  data/eUSD/data.json
  data/eUSD/logo.png
Labels: base-goerli

#408 Add TOWER Token
  data/TOWER/data.json
  data/TOWER/logo.svg
Labels: base-goerli

#400 Add Threshold Network Token (T) to Superchain Token List
  data/T/data.json
  data/T/logo.svg
Labels: Stale

#401 Added CHAIN token to the Base token list
  data/CHAIN/data.json
  data/CHAIN/logo.svg
Labels: base-goerli

#399 added MonkeyLeague (MBS) token
  data/MBS/data.json
  data/MBS/logo.png
Labels: base-goerli, base

#423 Add FARM token
  data/FARM/data.json
  data/FARM/logo.svg
Labels: base

#424 Add iFARM token
  data/IFARM/data.json
  data/IFARM/logo.svg
Labels: base

#429 Add COMP to Base
  data/COMP/data.json
Labels: base

#432 Add cbeth on base-goerli and base mainnet
  data/cbETH/data.json
Labels: base-goerli, base

#426 add HANeP to Base
  data/HANeP/data.json
Labels: base

#425 add HAN to Base
  data/HAN/data.json
Labels: base

#427 Add base dai deployment
  data/DAI/data.json
Labels: base
