Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-08, with the labels that each got.

#436 Add HOP to Base
  data/HOP/data.json
  data/HOP/logo.png
  data/HOP/logo.svg
Labels: base

#445 Add NFTE to Base
  data/NFTE/data.json
  data/NFTE/logo.png
Labels: base

#446 Add tBTC to Base
  data/tBTC/data.json
  data/tBTC/logo.svg
Labels: base

#457 Add SUSHI to Base
  data/SUSHI/data.json
Labels: waiting-for-pr-author-response, base

#460 Update BAL token
  data/BAL/data.json
Labels: base

#456 feat: add GRG on Base
  data/GRG/data.json
Labels: base

#455 Add PTY to Base-Goerli
  data/PTY/data.json
  data/PTY/logo.svg
Labels: waiting-for-pr-author-response, base

#440 new file: data/BLUE/data.json
  data/BLUE/data.json
  data/BLUE/logo.svg
Labels: base

#459 Added THALES token to Base mainnet
  data/THALES/data.json
Labels: base

#458 Add NOGS to base
  data/NOGS/data.json
  data/NOGS/logo.png
Labels: base

#470 Add chain token
  data/CHAIN/data.json
Labels: base-goerli

#462 fix: add crvUSD data + logo
  data/crvUSD/data.json
  data/crvUSD/logo.svg
Labels: base

#471 Add SUS to Base
  data/SUS/data.json
  data/SUS/logo.png
Labels: base

#433 Update chains.ts
  src/chains.ts
Labels: waiting-for-pr-author-response

#495 Add DOG to token registry
  data/DOG/data.json
  data/DOG/logo.svg
Labels: base
