Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2023-10, with the labels that each got.

#536 Add base address of TETU
  data/TETU/data.json
  data/TETU/logo.svg
Labels: base

#508 Add Spot token to Base Bridges
  data/SPOT/data.json
  data/SPOT/logo.svg
Labels: bug, question, requires-manual-review, base

#554 Add l1 USDC tokens to `BridgedUSDC`
  data/BridgedUSDC/data.json
Labels: do-not-merge
