Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-09, with the labels that each got.

#915 Add MUGLOO to Op
  data/MUGLOO/data.json
  data/MUGLOO/logo.svg
Labels: op

#924 Add yETH to Base
  data/yETH/data.json
  data/yETH/logo.svg
Labels: base

#925 Add MUGLOO to Base
  data/MUGLOO/data.json
Labels: base

#934 Added NOVA token
  data/NOVA/data.json
  data/NOVA/logo.png
Labels: base

#935 Add MASQ
  data/MASQ/data.json
  data/MASQ/logo.png
Labels: base

#936 feat: add support for ASI token
  data/ASI/data.json
  data/ASI/logo.svg
Labels: base

#923 add TRB networks for base
  data/TRB/data.json
Labels: waiting-for-pr-author-response, base

#937 Add TRUE token to base sepolia
  data/TRUE/data.json
  data/TRUE/logo.svg
Labels: base

#942 Feat : Add CTRAVL token to the OP and Base mainnet network
  data/CTRAVL/data.json
  data/CTRAVL/logo.svg
Labels: base, op

#938 Add TRB to Lisk
  data/TRB/data.json
Labels: lisk

#943 add spx to token list
  data/SPX/data.json
  data/SPX/logo.svg
Labels: waiting-for-pr-author-response, base

#947 GALAXIS Token
  data/GALAXIS/data.json
  data/GALAXIS/logo.svg
Labels: base
