Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-02, with the labels that each got.

#631 Add MET to BASE
  data/MET/data.json
Labels: base

#628 Modified TKN to add bridged Base token address
  data/TKN/data.json
Labels: base

#635 Add BTRST Sepolia and Goerli and Base addresses
  data/BTRST/data.json
Labels: base

#629 [Base] Add Brickken BKN
  data/BKN/data.json
  data/BKN/logo.svg
Labels: base

#609 add pndr token
  data/PNDR/data.json
  data/PNDR/logo.png
Labels: Stale, base

#579 Add USDT token address in Mode chain
  data/USDT/data.json
  src/chains.ts
Labels: waiting-for-pr-author-response
