Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-12, with the labels that each got.

#1009 Add Silo on Optimism
  data/Silo/data.json
Labels: op

#1022 Update CXT logo
  data/CXT/logo.svg
Labels: base

#1021 Add NSTR token to Base
  data/NSTR/data.json
  data/NSTR/logo.svg
Labels: base

#1017 Add Cryptoodles Toodle token to base
  data/TODL/data.json
  data/TODL/logo.png
Labels: base

#1016 Add Bobo to Base
  data/BOBO/data.json
  data/BOBO/logo.svg
Labels: base

#1015 add 0xBitcoin Address to Base
  data/0xBTC/data.json
Labels: base

#1014 add Heurist to Base
  data/HEU/data.json
  data/HEU/logo.svg
Labels: base

#1005 Add OL Token Mainnet
  data/OL/data.json
Labels: waiting-for-pr-author-response, base

#997 adding PolySwarm
  data/NCT/data.json
  data/NCT/logo.svg
Labels: base

#1013 Add MRSMIGGLES to Base
  data/MRSMIGGLES/data.json
  data/MRSMIGGLES/logo.svg
Labels: waiting-for-pr-author-response, base

#1023 Lizcoin (LIZ) configuration added for Ethereum mainnet / BASE mainnet
  data/LIZCOIN/data.json
Labels: base

#1012 Add Ucash Token to Base
  data/UCASH/data.json
  data/UCASH/logo.svg
Labels: waiting-for-pr-author-response, base

#1010 Add NET (Nektar Network) to token list
  data/NET/data.json
  data/NET/logo.svg
Labels: waiting-for-pr-author-response, base

#1032 Add the MINDS token
  data/MINDS/data.json
  data/MINDS/logo.svg
Labels: base

#1031 Add GLS to Base
  data/GLS/data.json
  data/GLS/logo.svg
Labels: base

#1033 Add MASK on Base
  data/MASK/data.json
Labels: base

#1034 Add IDRISS on Base to Superchain token list
  data/IDRISS/data.json
  data/IDRISS/logo.svg
Labels: base
