Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-06, with the labels that each got.

#839 Add Cryptex token to Base
  data/CTX/data.json
  data/CTX/logo.svg
Labels: base

#842 Add USC token
  data/USC/data.json
  data/USC/logo.svg
Labels: base

#841 Update BOME on BASE
  data/BOME/data.json
  data/BOME/logo.svg
Labels: base

#844 Add NOUNS
  data/NOUNS/data.json
  data/NOUNS/logo.png
Labels: base

#846 Include TKAI
  data/TKAI/data.json
  data/TKAI/logo.svg
Labels: base

#847 feat: added bepro token
  data/BEPRO/data.json
  data/BEPRO/logo.svg
Labels: base

#848 feat: YOKAI 👺 — Add YOKAI token to BASE network
  data/YOKAI/data.json
  data/YOKAI/logo.svg
Labels: base

#850 XY Oracle token
  data/XYO/data.json
  data/XYO/logo.svg
Labels: base, op

#851 :art: [support] Add TYBENG for BASE Sepolia [testnet]
  data/TYBENG/data.json
Labels: base

#857 Revert "Add base L2 token address for MKR"
  data/MKR/data.json
Labels: base

#858 Add MOOV token
  data/MOOV/data.json
  data/MOOV/logo.svg
Labels: base

#859 Add LOCG Token
  data/LOCG/data.json
  data/LOCG/logo.png
Labels: base

#860 Add AXGT Token
  data/AXGT/data.json
  data/AXGT/logo.svg
Labels: base

#856 Add OGN token
  data/OGN/data.json
  data/OGN/logo.svg
Labels: base

#854 add GGTK token
  data/GGTK/data.json
  data/GGTK/logo.svg
Labels: base

#866 Add AIKEK token
  data/AIKEK/data.json
  data/AIKEK/logo.svg
Labels: base

#868 Add $SKAI token
  data/SKAI/data.json
  data/SKAI/logo.svg
Labels: waiting-for-pr-author-response, base

#872 Add BURN to Base Chain
  data/BURN/data.json
  data/BURN/logo.png
Labels: base

#863 Add WEXO token
  data/WEXO/data.json
  data/WEXO/logo.png
Labels: base

#879 Adjusting $SKAI logo
  data/SKAI/logo.svg
Labels: base

#880 Adds THX Token
  data/THX/data.json
  data/THX/logo.svg
Labels: base
