Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-05, with the labels that each got.

#699 Add FLI Token
  data/FLI/data.json
  data/FLI/logo.svg
Labels: base

#817 Add $DOSE token to Base
  data/DOSE/data.json
  data/DOSE/logo.svg
Labels: base

#812 add CHAR on Base
  data/CHAR/data.json
  data/CHAR/logo.svg
Labels: base

#808 HOBA token on Base
  data/HOBA/data.json
  data/HOBA/logo.svg
Labels: base

#807 Add base L2 token address for MKR
  data/MKR/data.json
Labels: base

#802 Add EthicHub (ETHIX) token
  data/ETHIX/data.json
  data/ETHIX/logo.svg
Labels: base

#801 Add Ambire Wallet to Base
  data/WALLET/data.json
  data/WALLET/logo.svg
Labels: base

#797 wPOKT on Base
  data/wPOKT/data.json
  data/wPOKT/logo.svg
Labels: base

#800 Add rgUSD base
  data/rgUSD/data.json
  data/rgUSD/logo.svg
Labels: base

#785 PRE token (Presearch) for Base
  data/PRE/data.json
  data/PRE/logo.svg
Labels: base

#784 Add TT token ( testing token )
  data/TT/data.json
  data/TT/logo.svg
Labels: waiting-for-pr-author-response, base

#751 tscTokenPullRequest
  data/TSC/data.json
  data/TSC/logo.png
Labels: base

#693 Add zunUSD and zunETH to Optimism and Base
  data/zunETH/data.json
  data/zunETH/logo.svg
  data/zunUSD/data.json
  data/zunUSD/logo.svg
Labels: base, op

#688 feat: add ZOOMER
  data/ZOOMER/data.json
  data/ZOOMER/logo.png
Labels: base

#828 Updated GENOME/logo.svg to proper svg content
  data/GENOME/data.json
  data/GENOME/logo.svg
Labels: base

#826 Add HAIR token to Base
  data/HAIR/data.json
Labels: base

#821 PSTAKE token on Base
  data/PSTAKE/data.json
  data/PSTAKE/logo.png
Labels: base

#819 Add EthiHub token (ETHIX) on base mainnet and remove sepolia testnets tokens.
  data/ETHIX/data.json
Labels: base

#818 MANTRA token on Base
  data/OM/data.json
  data/OM/logo.png
Labels: base

#775 Added IMGNAI
  data/IMGNAI/data.json
  data/IMGNAI/logo.svg
Labels: base

#820 JAM token on Base
  data/JAM/data.json
  data/JAM/logo.svg
Labels: base

#827 wHOGE data
  data/wHOGE/data.json
  data/wHOGE/logo.svg
Labels: base

#824 add ZUN token data
  data/ZUN/data.json
  data/ZUN/logo.svg
Labels: base, op

#792 Base address for UNI
  data/UNI/data.json
Labels: base

#833 Update LIKE data.json (update token symbol to match contract)
  data/LIKE/data.json
Labels: base

#834 add FACTR token
  data/FACTR/data.json
  data/FACTR/logo.png
Labels: base

#830 add token dbDEGEN
  data/dbDEGEN/data.json
  data/dbDEGEN/logo.svg
Labels: base

#829 Update data.json for USDC sepolia
  data/USDC/data.json
Labels: waiting-for-pr-author-response, base

#723 added GMAC
  data/GMAC/data.json
  data/GMAC/logo.svg
Labels: op

#667 Add SMT token support to the Optimism network
  data/SMT/data.json
Labels: waiting-for-pr-author-response, op

#838 docs(README): Drop req to tag Base maintainer
  README.md
Labels: base

#837 Add WGC to Base token list
  data/WGC/data.json
  data/WGC/logo.svg
Labels: base

#836 Add CIG to Base
  data/CIG/data.json
  data/CIG/logo.svg
Labels: base
