Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-07, with the labels that each got.

#891 Add Silo Governance Token to Base
  data/Silo/data.json
  data/Silo/logo.svg
Labels: base

#895 pStake logo update on Base
  data/PSTAKE/data.json
  data/PSTAKE/logo.png
Labels: base

#889 add YYY token
  data/YYY/data.json
  data/YYY/logo.svg
Labels: base

#893 Adds auraBAL token
  data/auraBAL/data.json
  data/auraBAL/logo.svg
Labels: base

#896 Add Pepe's Dog (POPO) to Superchain Token List
  data/POPO/data.json
  data/POPO/logo.svg
Labels: base

#876 Add 🇺🇸
  data/CENT/data.json
  data/CENT/logo.svg
Labels: waiting-for-pr-author-response, base

#894 feat: adds AURA token
  data/AURA/data.json
  data/AURA/logo.svg
Labels: base, op

#890 Add OPENLOOT token
  data/OPENLOOT/data.json
  data/OPENLOOT/logo.svg
Labels: base

#901 Add NEURON
  data/NEURON/data.json
  data/NEURON/logo.svg
Labels: base

#902 Adds CNG token
  data/CNG/data.json
  data/CNG/logo.svg
Labels: op

#883 Add sDAI ERC20 on Mode.
  data/sDAI/data.json
Labels: Stale, mode
