Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2024-10, with the labels that each got.

#955 Update VUSD logo
  data/VUSD/logo.svg
Labels: base

#956 Add YGG to Base
  data/YGG/data.json
  data/YGG/logo.svg
Labels: base

#958 doc: Add IRARA Token for future cross-chain on Mainnet
  data/IRARA/data.json
  data/IRARA/logo.svg
Labels: base, op

#968 Add SPC, VSP and VUSD to Optimism
  data/SPC/data.json
  data/VSP/data.json
  data/VUSD/data.json
Labels: op

#957 Add CTRAVL token to Metal-l2
  data/CTRAVL/data.json
Labels: requires-manual-review

#969 Add Bridged USDC to Lisk
  data/BridgedUSDC/data.json
Labels: lisk

#952 Add Glo Dollar (USDGLO)
  data/USDGLO/data.json
  data/USDGLO/logo.svg
Labels: base, op
