Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2025-04, with the labels that each got.

#1018 add AJNA on OP Mainnet
  data/AJNA/data.json
Labels: op

#1113 Remove Mergify
  .github/mergify.yml
Labels: do-not-merge

#1026 Update README.md
  README.md
Labels: requires-manual-review, waiting-for-pr-author-response, op

#1047 Add MTL token
  data/MTL/data.json
  data/MTL/logo.svg
Labels: metal

#1086 fix spelling errors
  README.md
  bin/cli.ts
Labels: requires-manual-review, op

#1087 add: new SMT addresses for Mode and Lisk networks
  data/SMT/data.json
Labels: mode, lisk

#1093 Added support for QUICK on soneium
  data/QUICK/data.json
  data/QUICK/logo.svg
Labels: soneium

#1101 add IDRX
  data/IDRX/data.json
  data/IDRX/logo.svg
Labels: base, lisk

#1024 Updating BICO token address on optimism
  data/BICO/data.json
Labels: waiting-for-pr-author-response, op

#1108 Add MVL token
  data/MVL/data.json
  data/MVL/logo.svg
Labels: base

#1127 Add MVL token
  data/MVL/data.json
  data/MVL/logo.svg
Labels: base

#1112 Add GYFI token
  data/GYFI/data.json
  data/GYFI/logo.svg
Labels: base

#1117 Add CATTBUTT token
  data/CATTBUTT/data.json
  data/CATTBUTT/logo.svg
Labels: base

#1126 Add BRZ Token
  data/BRZ/data.json
  data/BRZ/logo.svg
Labels: base, op

#1129 Add USD₮0 token
  data/USD₮0/data.json
  data/USD₮0/logo.png
Labels: base, mode, lisk, soneium

#1124 Add XAUt token
  README.md
  data/XAUt/data.json
  data/XAUt/logo.svg
Labels: celo
