Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2025-05, with the labels that each got.

#1132 update: add sepolia and base-sepolia addresses for BTREE token
  data/BTREE/data.json
Labels: base

#1133 Add STS token to Superchain Token List
  data/STS/data.json
  data/STS/logo.svg
Labels: base

#1140 Add GFI token metadata and add it to Base
  data/GFI/data.json
  data/GFI/logo.svg
Labels: base

#1152 update: add ethereum and base addresses for ICNT token
  data/ICNT/data.json
Labels: base

#1135 Add more tokens for Celo blockchain
  data/1INCH/data.json
  data/ACX/data.json
  data/DAI/data.json
  data/DOLA/data.json
  data/GTC/data.json
  data/LDO/data.json
  data/LINK/data.json
  data/LUSD/data.json
  data/MKR/data.json
  data/POOL/data.json
  data/RPL/data.json
  data/UMA/data.json
  data/WLD/data.json
  data/crvUSD/data.json
  data/rETH/data.json
  data/sDAI/data.json
Labels: celo

#1155 Added TRALA TOKEN
  data/TRALA/data.json
  data/TRALA/logo.svg
Labels: soneium
