Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2025-02, with the labels that each got.

#1059 Add fear token
  data/FEAR/data.json
  data/FEAR/logo.svg
Labels: waiting-for-pr-author-response, base

#1063 added AIP
  data/AIP/data.json
  data/AIP/logo.svg
Labels: waiting-for-pr-author-response, base

#1067 Add FLAY token
  data/FLAY/data.json
  data/FLAY/logo.svg
Labels: base

#1069 Add SOSO token
  data/SOSO/data.json
  data/SOSO/logo.svg
Labels: base

#1068 Add KRL token on Base and Optimism
  data/KRL/data.json
  data/KRL/logo.svg
Labels: base, op

#1066 Add XRING and XKTON token on Base and Optimism
  data/XKTON/data.json
  data/XKTON/logo.svg
  data/XRING/data.json
  data/XRING/logo.svg
Labels: base, op

#1076 Add wstETH to Lisk and Lisk Sepolia
  data/wstETH/data.json
Labels: lisk

#1085 Add NEUY token to Base
  data/NEUY/data.json
  data/NEUY/logo.png
Labels: base

#1078 add KIT
  data/KIT/data.json
  data/KIT/logo.svg
Labels: base

#1075 feat: Add support for Soneium Mainnet and Testnet
  README.md
  src/chains.ts
  src/schemas.ts
  src/types.ts
Labels: requires-manual-review, op

#984 Add UTU Coin to standard bridge for lisk and lisk-sepolia.
  data/UTU/data.json
  data/UTU/logo.svg
Labels: lisk

#1084 Add BTREE token
  data/BTREE/data.json
  data/BTREE/logo.svg
Labels: waiting-for-pr-author-response, base

#1060 Deploy Shutter on base
  data/SHU/data.json
Labels: waiting-for-pr-author-response, base
