Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2025-01, with the labels that each got.

#1038 ✨ add AAVE token on base
  data/AAVE/data.json
Labels: base

#1040 Add SOVRN to Base
  data/SOVRN/data.json
  data/SOVRN/logo.svg
Labels: base

#1037 Add RSS3 Token
  data/RSS3/data.json
  data/RSS3/logo.png
Labels: base

#1036 Add PSY
  data/PSY/data.json
  data/PSY/logo.svg
Labels: waiting-for-pr-author-response, base

#1043 Add ZENT token to Base
  data/ZENT/data.json
  data/ZENT/logo.svg
Labels: base

#1044 Add stZENT to Base
  data/stZENT/data.json
  data/stZENT/logo.svg
Labels: base

#1049 feat(pgn): Deprecate Public Goods Network
  README.md
  data/DAI/data.json
  data/USDT/data.json
  optimism.tokenlist.json
  src/chains.ts
  src/schemas.ts
  src/types.ts
Labels: requires-manual-review, op

#1050 Add Tether deployment on Base
  data/USDT/data.json
Labels: base

#1048 Adding L2 SNT addresses for Base and Base Sepolia
  data/SNT/data.json
Labels: base

#1051 Add $AZUR Token
  data/AZUR/data.json
  data/AZUR/logo.svg
Labels: base

#1056 Added UOMI token
  data/UOMI/data.json
  data/UOMI/logo.svg
Labels: base

#1055 Add LEGEND to token list
  data/LEGEND/data.json
  data/LEGEND/logo.svg
Labels: base

#1042 Add HEX Token
  data/HEX/data.json
  data/HEX/logo.svg
Labels: base

#1052 Add PERP Token
  data/PERP/data.json
Labels: base

#1053 Add MAX token to Base
  data/MAX/data.json
  data/MAX/logo.png
Labels: base

#1054 Add Telcoin Profile
  data/TEL/data.json
  data/TEL/logo.svg
Labels: base

#990 add DIMO token to optimism
  data/DIMO/data.json
Labels: op
