Repository ethereum-optimism/ethereum-optimism.github.io, pull requests merged in 2025-03, with the labels that each got.

#1098 Add ADS token to Base
  data/ADS/data.json
  data/ADS/logo.svg
Labels: base

#1089 Add MNRY token to Base
  data/MNRY/data.json
  data/MNRY/logo.svg
Labels: base

#1079 Add PMON
  data/PMON/data.json
  data/PMON/logo.svg
Labels: waiting-for-pr-author-response, base

#1097 add BOSON on OP Mainnet
  data/BOSON/data.json
Labels: op

#1099 Add DHK DAO token to Superchain Token List
  data/DHK/data.json
  data/DHK/logo.svg
Labels: op

#1103 Add ICNT to Base Sepolia
  data/ICNT/data.json
  data/ICNT/logo.svg
Labels: base
